# Deployment v5
name: Deploy To Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "HF_TOKEN is missing"
            exit 1
          fi

          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          rm -rf hf_space

          git clone https://oauth2:$HF_TOKEN@huggingface.co/spaces/prateek-singh24/agentic-ai-factory-demo hf_space

          rsync -av \
            --exclude='.git' \
            --exclude='hf_space' \
            --exclude='__pycache__' \
            --exclude='*.pyc' \
            ./ hf_space/

          cd hf_space

          git remote set-url origin https://oauth2:$HF_TOKEN@huggingface.co/spaces/prateek-singh24/agentic-ai-factory-demo

          git add .

          git commit -m "Auto deploy from GitHub" || echo "No changes to commit"

          git push origin main